# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 18:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Been',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Coffe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('esspresso', models.PositiveIntegerField(default=1)),
                ('water', models.FloatField(default=0)),
                ('steamed_milk', models.BooleanField(default=False)),
                ('extra', models.TextField()),
                ('been', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Been')),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Powder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Roast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Syrup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='coffe',
            name='poweder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Powder'),
        ),
        migrations.AddField(
            model_name='coffe',
            name='roat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Roast'),
        ),
        migrations.AddField(
            model_name='coffe',
            name='syrup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Syrup'),
        ),
    ]
