# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffe',
            name='poweder',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Powder'),
        ),
        migrations.AlterField(
            model_name='coffe',
            name='syrup',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Syrup'),
        ),
    ]
